version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # command: sh ./scripts/api.sh
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    restart: always
    tty: true
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DATABASE_HOST: localhost
    ports:
      - 5432:5432
